export const TOK = {
  textPrimary: 'var(--dsw-alias-label-primary, #0f1115)',
  textSecondary: 'var(--dsw-alias-label-secondary, #61666b)',
  textTertiary: 'var(--dsw-alias-label-tertiary, #81858c)',
  border: 'var(--dsw-alias-border-l1, rgba(0,0,0,.04))',
  switchOn: 'var(--dsw-alias-state-business-primary, #4176e6)',
  switchOff: 'var(--dsw-alias-border-l2, rgba(0,0,0,.1))',
  switchThumb: 'var(--dsw-alias-bg-layer-1, #ffffff)',
  switchEase: 'var(--ds-ease-in-out, cubic-bezier(.4, 0, .2, 1))',
  menuBg: 'var(--dsw-specific-menu, #ffffff)',
  menuBorder: 'var(--dsw-alias-border-inverted, rgba(0,0,0,.1))',
  menuShadow: 'var(--dsw-shadow-lv3, 0 12px 32px rgba(0,0,0,.22))',
  bgBase: 'var(--dsw-alias-bg-base, #ffffff)',
  fontFamily:
    'var(--dsw-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif)',
  success: 'var(--dsw-alias-state-success-primary, #22c55e)',
  warn: 'var(--dsw-alias-state-warn-primary, #f59e0b)',
  error: 'var(--dsw-alias-state-error-primary, #ec1313)',
} as const;

export const PANEL_CSS = [
  '.ci-trigger:focus-visible,.ci-switch:focus-visible,.ci-iconbtn:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary,#4176e6);outline-offset:1px;border-radius:999px}',
  '.ci-disclosure-trigger:focus-visible,.ci-server-trigger:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary,#4176e6);outline-offset:1px;border-radius:4px}',
  '.ci-tab:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary,#4176e6);outline-offset:1px;border-radius:6px}',
  '.ci-trigger:hover,.ci-iconbtn:hover,.ci-server-trigger:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(38,49,72,.06))}',
  '.ci-switch:hover:not(:disabled){filter:brightness(1.12)}',
  '.ci-row-head{display:flex;align-items:center;gap:8px;padding:6px 8px;margin:0 -8px;border-radius:8px}',
  '.ci-row-head:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(38,49,72,.06))}',
  '.ci-row-head .ci-send{opacity:0;transition:opacity .12s}',
  '.ci-row-head:hover .ci-send,.ci-row-head:focus-within .ci-send{opacity:1}',
  '.ci-filter:focus{border-color:var(--dsw-alias-state-business-primary,#4176e6)}',
  '.ci-filter:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary,#4176e6);outline-offset:0}',
  '.ci-filter::placeholder{color:var(--dsw-alias-label-tertiary,#81858c)}',
  '.ci-panel{transform-origin:var(--transform-origin);transition:opacity .14s var(--ds-ease-in-out,ease),transform .14s var(--ds-ease-in-out,ease)}',
  '.ci-panel[data-starting-style],.ci-panel[data-ending-style]{opacity:0;transform:scale(.96) translateY(4px)}',
  '.ci-collapse{height:var(--collapsible-panel-height);transition:height .14s var(--ds-ease-in-out,ease);overflow:hidden}',
  '.ci-collapse[data-starting-style],.ci-collapse[data-ending-style]{height:0}',
  '.ci-toolrow{content-visibility:auto;contain-intrinsic-size:auto 30px}',
  '.ci-disclosure-trigger{min-width:0;display:flex;align-items:center;gap:6px;flex:1 1 auto;padding:0;border:0;background:transparent;color:inherit;font:inherit;text-align:left;cursor:pointer}',
  '.ci-disclosure-trigger:disabled,.ci-server-trigger:disabled{cursor:default}',
  '.ci-disclosure-trigger:hover .ci-name{color:var(--dsw-alias-label-primary,#0f1115)}',
  '.ci-description{padding:3px 0 0 24px;line-height:18px;color:var(--dsw-alias-label-tertiary,#81858c);word-break:break-word}',
  '.ci-chevron{display:grid;place-items:center;width:18px;height:18px;flex:none;color:var(--dsw-alias-label-tertiary,#81858c);border-radius:4px}',
  '.ci-chevron svg{transition:transform .12s var(--ds-ease-in-out,ease)}',
  '.ci-server-trigger[aria-expanded="true"] .ci-chevron svg,.ci-disclosure-trigger[aria-expanded="true"] .ci-chevron svg{transform:rotate(90deg)}',
  '.ci-tabs{display:flex;gap:2px;padding:2px;border-radius:8px;background:var(--dsw-alias-bg-base,#ffffff);border:1px solid var(--dsw-alias-border-l1,rgba(0,0,0,.04))}',
  '.ci-tab{flex:1;height:24px;border:none;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary,#61666b);font:inherit;font-size:12px;line-height:1;cursor:pointer;font-variant-numeric:tabular-nums;padding:0 4px}',
  '.ci-tab:hover{color:var(--dsw-alias-label-primary,#0f1115)}',
  '.ci-tab[data-active]{background:var(--dsw-specific-menu,#fff);color:var(--dsw-alias-label-primary,#0f1115);box-shadow:0 1px 2px rgba(0,0,0,.08)}',
  '@media (prefers-reduced-motion: reduce){.ci-thumb,.ci-panel,.ci-collapse,.ci-chevron svg{transition:none !important}}',
].join('\n');
